# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9";
      sha256 = "1hrybsql68xw57brzj805xx2mghydpdiysv3gbhr7f5wlxj2514y";
    };
  }
  {
    goPackagePath = "github.com/coreos/go-systemd";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/go-systemd";
      rev = "127658326aaff7892c7d60c29657c6e6c440ad7e";
      sha256 = "1qckr877q9yigkw73l76fwrx6y4d9hv5057xa6y7qcn8d33jdpjm";
    };
  }
  {
    goPackagePath = "github.com/coreos/pkg";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/pkg";
      rev = "97fdf19511ea361ae1c100dd393cc47f8dcfa1e1";
      sha256 = "1srn87wih25l09f75483hnxsr8fc6rq3bk7w1x8125ym39p6mg21";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "bbd03ef6da3a115852eaf24c8a1c46aeb39aa175";
      sha256 = "1pyli3dcagi7jzpiazph4fhkz7a3z4bhd25nwbb7g0iy69b8z1g4";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "c12348ce28de40eed0136aa2b644d0ee0650e56c";
      sha256 = "1d0c1isd2lk9pnfq2nk0aih356j30k3h1gi2w0ixsivi5csl7jya";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "c3324c1198cf3374996e9d3098edd46a6b55afc9";
      sha256 = "19qcz5bpzj5kqyhmbq5kxr8nrqqlszazzq6w0wldis1yk1wwww00";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c";
      sha256 = "19y4ywsivhpxj7ikf2j0gm9k3cmyw37qcbfi78n526jxcc7kw998";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "e4aa40a9169a88835b849a6efb71e05dc04b88f0";
      sha256 = "0m1n616d694jca0qjwjn5ci7scfgm2jpi94dhi356arm9lhda4jc";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "54d17b57dd7d4a3aa092476596b3f8a933bde349";
      sha256 = "1b5218hi6k9i637k6xc7ynpll577zbnrhjm9jr2iczy3j0rr4rvr";
    };
  }
]
